### ISSUE TITLE
avatar/buddy icon

### ISSUE THREAD

**Issue by C0NTi** [LordBoos/discord_game#1]
Many thanks for making this component,

I am in the process of moving away from my current ( very slow )discord rest sensor implementation  over to your component - much more streamlined config.

Is there any way of making your component use the discord avatar/buddy icon as entity_picture or store it as attribute?

here is a snapshot of my rest sensor....
![Capture](https://user-images.githubusercontent.com/29498865/62575980-d123d300-b893-11e9-86c9-b29f07ec631e.PNG)

**Comment by LordBoos** [comment]
Good idea, I'll look into it.

**Comment by LordBoos** [comment]
Added in #2 
This will be available in HACS in the next release 1.1
