### ISSUE TITLE
all users went unavailable after i enabled SSL on my home assistant 

### ISSUE THREAD

**Issue by Sloth-on-meth** [LordBoos/discord_game#20]
Hi there! since i switched to HTTPS, my discord game integration stopped working. any ideas?

**Comment by LordBoos** [comment]
Hello, I'm sorry you have such an issue. I'm using SSL without any issues. Even tried multiple approaches like native HA SSL with let's encrypt and also nginx reverse proxy. 
Is the bot present on your discord server? 
Are there any errors in your Home Assistant log?

**Comment by Sloth-on-meth** [comment]
Hi there, apparently rich presence was somehow disabled on my discord bot. i enabled it in the discord dev portal and it works again. was a coincidence with the SSL change, closed!
