### ISSUE TITLE
rebooted last night, now everyone is "unknown"

### ISSUE THREAD

**Issue by bendiger** [LordBoos/discord_game#21]
I've tried updating the token, changing to user IDs, deleting the component and reinstalling, and rolling back to previous versions. Nothing works. When I rebooted, I wasn't even editing any ymal for discord, it just stopped updating. Not sure what else to try.

~Ben

**Comment by LordBoos** [comment]
Hello, I'm sorry you have such an issue.
Is the bot present on your discord server? 
Are there any errors in your Home Assistant log?

**Comment by rvst1104** [comment]
I do have the exact same error. Also tried to roll back to 3.2.1.
Last time I got a status was yesterday evening (21:16 Berlin Time).  
Bot also seems to be online.
<img width="290" alt="2020-10-28 14_57_41-Dashboard - Home Assistant" src="https://user-images.githubusercontent.com/64125185/97446430-ae655a80-192e-11eb-9c89-db83dc72f6b5.png">
<img width="179" alt="2020-10-28 15_01_46-#songs - Discord" src="https://user-images.githubusercontent.com/64125185/97446440-aefdf100-192e-11eb-9650-32fbdf01162a.png">

**Comment by bendiger** [comment]
Identical to rvst1104. Mine happened at 4:26 CST Chicago time. Bots online in discord. If I change the token to something wrong, the bot will go offline. So It is connecting, just not gathering data.

**Comment by LordBoos** [comment]
I was able to reproduce the issue. The was a change in Discord bot privileges and you now have to explicitly allow bot to gather server members and presence data.
Enable following options in your bot configuration, restart your HA and it should fix the issue. It helped in my case.
![image](https://user-images.githubusercontent.com/939813/97451561-25512200-1934-11eb-80e5-68ae845d0997.png)

**Comment by rvst1104** [comment]
Thats it! Enaled both options, restarted HA and my sensors are back working again. Thank you so much for your help!
