### ISSUE TITLE
(More) problems with Intents?

### ISSUE THREAD

**Issue by mariwing** [LordBoos/discord_game#23]
I am getting this error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/discord_game/sensor.py", line 37, in async_setup_platform
    intents = discord.Intents.default()
AttributeError: module 'discord' has no attribute 'Intents'

I have granted my bot the two new privliges mentioned in the recently updated readme.md. The stock Discord component works as my notifications shows up in the channel as before.

I am running Home Assistant 117.2 and Discord Game 3.3.1.

Any tips on what I can do to get back the game stats? Thanks!

**Comment by LordBoos** [comment]
This looks like dependency problem.
Intents are supported from discord.py v1.5.0.
While stock Discord component uses 1.4.1, Discord Game uses 1.5.1.
Personally I'm able to use both components at the same time without issues. On HA restart, I can see in the log, that python installed discord.py 1.5.1.

Are you on hassio? You can try to disable the stock component, restart HA, then enable it and restart again.

**Comment by mariwing** [comment]
Thank you for your swift reply. I am using hassio. I tried your suggestion. After disabling the stock Discord component the Discord Game component started working again. Unfortunately after re-enabling stock Discord it again failed. I guess there is not much that can be done with this type of dependency conflict?

**Comment by LordBoos** [comment]
There is not much I can do from my side. This requires upgrading discord.py dependency in the Home Assistant Core project.

**Comment by mariwing** [comment]
Of course you could do that and submit a PR, being a developer and all ;-) 

Jokes aside; thank you for explaining the issues. I will close the issue since we know what causes it :-)

**Comment by LordBoos** [comment]
I've opened PR to Home Assistant Core to upgrade dependency. I'll close this once it's merged.

**Comment by LordBoos** [comment]
PR was merged, this should be fixed in the next major version of HA.
