### ISSUE TITLE
Enhancement: HACS support

### ISSUE THREAD

**Issue by SublimePotato** [LordBoos/discord_game#24]
Hey and thanks for contributing your sensor. 
It would be an really nice addition for [HACS (home assistant community store)](https://hacs.xyz/) which would make installing and updating the sensor a breeze. 

Basically only a few describing files are needed ->https://hacs.xyz/docs/publish/start

**Comment by LordBoos** [comment]
It's already available at HACS.

**Comment by LordBoos** [comment]
Or at least it was and I can still see it in the HACS. You can't find it there in integrations?

**Comment by SublimePotato** [comment]
It's there, my bad
