### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'discord_game'.

### ISSUE THREAD

**Issue by cannedpeanut** [LordBoos/discord_game#26]
On the newer versions of HA, I'm getting this error in my log when the HA service starts:

No 'version' key in the manifest file for custom integration 'discord_game'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'discord_game'

Version | core-2021.3.2
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
Virtual Environment | true
Python Version | 3.8.5
Operating System Family | Linux
Operating System Version | 5.4.103-1-pve
CPU Architecture | x86_64
Timezone | America/Denver

GitHub API | ok
Github API Calls Remaining | 4813
Installed Version | 1.11.3
Stage | running
Available Repositories | 775
Installed Repositories | 8

**Comment by LordBoos** [comment]
Fixed in 3.3.2
