### ISSUE TITLE
Home Assistant 2021.6 compatibility

### ISSUE THREAD

**Issue by User5981** [LordBoos/discord_game#27]
No 'version' key in the manifest file for custom integration 'discord_game'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'discord_game'

**Comment by LordBoos** [comment]
Are you on version 3.3.2? Version tag was added in that version.

**Comment by User5981** [comment]
The "Nothing new" in the changelog got me confused,
I should be on version 3.3.1, will update now. ;-)

**Comment by LordBoos** [comment]
Added more clarification of what was changed to changelog.
