### ISSUE TITLE
Discord user name changes cause entities to be renamed

### ISSUE THREAD

**Issue by jhqv** [LordBoos/discord_game#28]
First of all, thanks for an excellent integration!

The entity created by this integration contains both the Discord nick and the Discord numeric id, causing the entity to be renamed if the user changes the nickname (which many younger Discord users seem to do pretty frequently). This obviously breaks any other automations or Lovelace cards that rely on a fixed entity name.

Would it be possible for the integration to provide a somewhat static name for the entity instead?
For example `sensor.discord_user_<id>` instead of the current model with `sensor.discord_<nick>_<id>`.

**Comment by LordBoos** [comment]
Fixed in 70bdabd42e6cbf33f2d69b543574acf38051e017
Check release 3.4.0
