### ISSUE TITLE
Get users muted status?

### ISSUE THREAD

**Issue by bhoffmann84** [LordBoos/discord_game#29]
Hi,

I would love to automate a light to show red (on air) or green (muted) based on my discord muted state.

Is it possible to query this and add as sensor in HA?

Thanks a lot!

Bastian

**Comment by LordBoos** [comment]
Hi, 
it is possible, but it's limited. It can only be queried if user is currently in a voice channel.

It will be added in version 3.4.0.

**Comment by bhoffmann84** [comment]
Thanks for your great work and quick response! Looking forward to it :)
