### ISSUE TITLE
Game isn't reset as soon as user stops playing or goes offline

### ISSUE THREAD

**Issue by SmartHomeFanatic** [LordBoos/discord_game#31]
Hi!
After the update the "game" attribute isn't reset anymore when someone stops playing or goes offline.
Is this really the wanted behavior? When using the game attribute for automations this now stopped working.

![grafik](https://user-images.githubusercontent.com/41552156/119725276-0e45c480-be70-11eb-9906-0a618285b9b7.png)

**Comment by LordBoos** [comment]
This is definitely a bug, I'll look into it.

**Comment by LordBoos** [comment]
Fixed in https://github.com/LordBoos/discord_game/releases/tag/4.0.3
