### ISSUE TITLE
entity_id not using new format?

### ISSUE THREAD

**Issue by C0NTi** [LordBoos/discord_game#32]
Entity_ID not using new format.

I have migrated to your new version 4.# and ajusted my config to use discord user ids.

It is definitely working as I am seeing all the new attribute you have added.

It appears the unique_id is using the new format of sensor.discord_user_{id number} however the entity_ids themselves are still sensor.{discord_displayname]#{number}

![image](https://user-images.githubusercontent.com/29498865/120603926-6b2f1500-c444-11eb-8a92-9320f2262751.png)

**Comment by LordBoos** [comment]
This is weird because my own entities are using the new format. Could it be cached somewhere in your HA? Where did you get that JSON display?

**Comment by C0NTi** [comment]
I went full nuclear.

I deleted the component, manually removed all the entries from the registry. but for some reason they kept defaulting back to the old naming convention, no idea where else it could be cached.

In the end I just manually copied the unique_id to the entity_id and started home assistant and finally the old naming convention did not come back.

**Comment by LordBoos** [comment]
I will keep this open in for a while to see if it's happening for more users, especially new users.

**Comment by jhqv** [comment]
I am having the same issue a long time after upgrading. I have rebooted HA a few times since then, so that shouldn't be the issue. The entity id is still sensor.<username>_<numeric>.

![image](https://user-images.githubusercontent.com/8491785/121508606-12ccba00-c9e6-11eb-93d1-887077add2b6.png)

**Comment by LordBoos** [comment]
This is weird your entity_id don't even follow the old naming, which was sensor.discord_{name}#{discriminator}.
Are you sure you did not manualy edit those ID's in entity detail sometime in the past?
![image](https://user-images.githubusercontent.com/939813/121545244-a1ebc900-ca0a-11eb-8bc3-15ed82647121.png)

**Comment by jhqv** [comment]
> This is weird your entity_id don't even follow the old naming, which was sensor.discord_{name}#{discriminator}.
> Are you sure you did not manualy edit those ID's in entity detail sometime in the past?

Yes, it is possible that I edited the entity id a few weeks ago when I was struggling with the ids.
I can try removing it completely and reinstalling and see if that helps.

**Comment by trunks403** [comment]
Hello, i have also upgraded and entitiy are not using the correct format
My entitys name Sensor.username.idnumber

Is not problem for me cause it works :)

**Comment by LordBoos** [comment]
fixed in https://github.com/LordBoos/discord_game/commit/1825cdbe769185cb266387e88f6366dce0b9dc2f
