### ISSUE TITLE
Requirements not found: calendar

### ISSUE THREAD

**Issue by NemesisRE** [LordBoos/discord_game#33]
Hi,
just installed via HACS and configured like in described in the readme but after restarting HA I get 
the following message in the logs

`Platform error sensor.discord_game - Requirements for discord_game not found: ['calendar'].`

## System Health

version | core-2021.7.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.10
os_name | Linux
os_version | 5.11.0-22-generic
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4689
Installed Version | 1.13.2
Stage | running
Available Repositories | 912
Installed Repositories | 48

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 31
views | 9
mode | storage

</details>

**Comment by LordBoos** [comment]
Fixed in 4.2.1
