### ISSUE TITLE
Inviting Bot

### ISSUE THREAD

**Issue by riotm0de** [LordBoos/discord_game#35]
Hi,

the Instruction to invite a Bot is not working. 
You need to go to Menu "OAuth2" and click on BOT and then you get the working link to invite.
https://discordpy.readthedocs.io/en/stable/discord.html#inviting-your-bot

Cheers

**Comment by LordBoos** [comment]
Hi, thanks for reporting this. Looks like it was change on the Discord side and need to be updated here.

**Comment by LordBoos** [comment]
Actually I tested it and the old way still works. I added the link you posted as alternative way.
