### ISSUE TITLE
device_state_attributes Warning message in logs

### ISSUE THREAD

**Issue by rvst1104** [LordBoos/discord_game#38]
Since HomeAssistant 2021.12.0 I get the following message in the logs

`Entity sensor.discord_user_1234 (<class 'custom_components.discord_game.sensor.DiscordAsyncMemberState'>) implements device_state_attributes. Please report it to the custom component author.`

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 1:30:34 AM (4 occurrences)
Last logged: 1:30:34 AM

Entity sensor.discord_user_1234 (<class 'custom_components.discord_game.sensor.DiscordAsyncMemberState'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.discord_user_1235 (<class 'custom_components.discord_game.sensor.DiscordAsyncMemberState'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.discord_user_1236 (<class 'custom_components.discord_game.sensor.DiscordAsyncMemberState'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.discord_user_1237 (<class 'custom_components.discord_game.sensor.DiscordAsyncMemberState'>) implements device_state_attributes. Please report it to the custom component author.`

Reporting it with this issue here.

**Comment by LordBoos** [comment]
fixed in https://github.com/LordBoos/discord_game/commit/1825cdbe769185cb266387e88f6366dce0b9dc2f
