### ISSUE TITLE
Status updates not working

### ISSUE THREAD

**Issue by xiidoz** [LordBoos/discord_game#41]
Status updates are not pushed to Home Assistant. They are loaded correctly on restart, but are not updated on a running system.

**Comment by xiidoz** [comment]
This seems to be because nextcord separated presence update events in version 2.0: https://nextcord.readthedocs.io/en/stable/migrating_2.html?highlight=migrating#on-member-update-and-on-presence-update-separation

**Comment by LordBoos** [comment]
Fixed in https://github.com/LordBoos/discord_game/releases/tag/4.2.4
