### ISSUE TITLE
[FEATURE REQUEST] Bot Commands and messaging

### ISSUE THREAD

**Issue by ikrowni** [LordBoos/discord_game#45]
Not sure if its within the scope of the project but it would be cool if we could use the bot to perform actions based on home assistant triggers. For example i run a UFC discord and would love to have the bot embed a message with the upcoming calendar information i have coming into home assistant. Maybe a way to make announcements  that can @everyone when an event is about to kick off.

I looked around and didnt find much else as far as discord bots that would work with home assistant so figured i would ask and hope for the best here.

**Comment by LordBoos** [comment]
This is out of the scope of this project. 
But I think you can do that using official Home Assistant Discord integration which can send messages to a discord Channel, all you need is to create some automation with it: https://www.home-assistant.io/integrations/discord/
