### ISSUE TITLE
Discord integration stopped working on the 1st of September

### ISSUE THREAD

**Issue by Mithrox** [LordBoos/discord_game#46]
I use Discord integration to show status of certain users, and it's been running very good for months. Last night the status stopped updating and was stuck on the last status, and when I restarted HA server this morning to try to resolve it, it shows as "unknown" status. Nothing has been changed in my configuration, nor in the bot setup on the Discord developer page.

I have checked my setup, the users I am monitoring is stored in my sensor.yaml file like before, and there is nothing wrong with the setup.

I have checked the logs and there is an error repeating which I have put in here below.

PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

I do notice that the Discord bot is "offline" on my server, I do think it used to be online before.

Anyone else have any issues with this, or would be able to offer any advice? I have grown very accustomed to have the status updating regularly.

**Comment by Mithrox** [comment]
Just as note, my sensor.yaml looks like this, just like it always did.

- platform: discord_game
  token: <token Id key>
  image_format: webp
  members:
    - 3234xxxxxxxxxxxxxx
    - 3228xxxxxxxxxxxxxx

**Comment by LordBoos** [comment]
Hello, it is weird that it suddenly stopped working. From the error it seems that your privileged intents in discord bot configurations were somehow disabled. Can you check it? Go to https://discord.com/developers/applications/ select your bot there and check if the intents are enabled and enable them if disabled.
![image](https://user-images.githubusercontent.com/939813/188264558-a5033589-2e03-4895-b76b-d1a126c73e5f.png)

**Comment by Mithrox** [comment]
Hi and thank you for your reply. 

I did check, presence and server member intent was active like before, the last is not. I did try to turn them off and then rejoin server but same result. I also created a new both with intent on and joined it to the server, reconfigured sensor.yaml and restarted HA, but same result.

**Comment by LordBoos** [comment]
Please try the new updated version: https://github.com/LordBoos/discord_game/releases/tag/4.2.5
There were some changes in nextcord with intents that could've caused your issue.

**Comment by Mithrox** [comment]
> Please try the new updated version: https://github.com/LordBoos/discord_game/releases/tag/4.2.5 There were some changes in nextcord with intents that could've caused your issue.

Hi. Thank you for the quick turn-around.

Can I ask you how to change out the files, I seem to remember this was done through HACS originally? Is there a guide on how and where to replace the files?

**Comment by Mithrox** [comment]
Hi. Thank you for the new version, I updated through HACS and tried restarting my HA. I still these these same error messages and it does not seem to be working as it should.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/discord_game/sensor.py:60
Integration: discord_game (documentation)
First occurred: 22:19:07 (1 occurrences)
Last logged: 22:19:07

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/discord_game/sensor.py", line 60, in start_server
    await bot.start(token)
  File "/usr/local/lib/python3.10/site-packages/nextcord/client.py", line 673, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.10/site-packages/nextcord/client.py", line 614, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
nextcord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by LordBoos** [comment]
That is weird, it's working for me perfectly so it must really be something with your bot. Are you sure your discord bot token is the correct one with enabled intents? Are you using the bot on your only server? On the Discord page it states, that when the bot is used on 100 or more servers, you will need some kind of verification and approval, probably form Discord staff, but that probably is not your case right?

**Comment by Mithrox** [comment]
Yes, this time I started completely over again as well to make sure. I updated from HACS, I checked my configuration on sensor.yaml, I created a completely new bot with the directions you've put out, and which worked perfect the first time. I added the bot to my server, I'm only using the bot on one single server, my own. As you see from this image, both the bots are there and added.

![image](https://user-images.githubusercontent.com/58890682/188286922-a81fd796-da72-4c93-afa5-55163ea500d2.png)

I have checked the setup in the Bot sections, its like this:

![image](https://user-images.githubusercontent.com/58890682/188286955-7dae088c-f76e-4036-af4a-d90071107181.png)

I get the same error again in the log files as the previous restart.

Question, did you get these errors before you created the new version?

**Comment by Mithrox** [comment]
I tried yet another time, this time I removed all of discord_game from HACS and config/custom_components, restarted HA without the info in sensor.yaml. Then installed it again from HACS, restarted HA, then put the data in sensor.yaml, and then restarted again. Still same error messages.

**Comment by LordBoos** [comment]
I did not get the errors before, but I was using slightly different version before. Now I'm using [5.0.0-alpha.4](https://github.com/LordBoos/discord_game/tree/5.0.0-alpha.4) which is also available on HACS, but only difference is that it has a reactions feature. You can try that version if you want but it should not make a difference.

**Comment by Mithrox** [comment]
Can I just change out the 3 files in the discord_game folder, or do I need to do anything else? I am not sure how to enable beta version in HACS, never used them before.

**Comment by LordBoos** [comment]
Yes, you can replace the files.

**Comment by Mithrox** [comment]
Same result. Very weird. I don't know what is wrong, as nothing was done to the Discord server, nothing was done on the HA server, it just stopped working 2 nights ago.

**Comment by LordBoos** [comment]
It must be some kind of a bug with Discord itself. I'd suggest to contatct Discord support, maybe they can resolve it.

**Comment by Mithrox** [comment]
I will try, not sure if they will be very helpful considering the server is running without any issues for users, but I can try. Thank you for your effort, really hope I can get this back up and running soon.

**Comment by Mithrox** [comment]
One question, your bot in your server, does it show offline or online? Mine used to be online but now it's always offline, and so is the new one I created. I assume that has nothing to do with this?

**Comment by LordBoos** [comment]
My bot is only, but it's expected that your's is offline because you discord_game component failed to load because of those intents. Bot is only online when you Home Assistant is online and your discord_game starts properly.

**Comment by Mithrox** [comment]
I created a whole new HA instance on my NAS and then did the HACS install and your latest beta install. I installed only discord_game, and then I created a new application and a bot with the Discord Developer site. I then enabled all 3 intents, Message Content intent as well, and it worked straight away on my new install. I then configured the original HA with the new Application/bot, and it also worked. So I guess the issue I had the whole way (or my theory is), that the bot now need all 3 intents to work. I will test more later with the older bots and enable all on them too, but right now I'm just happy to have it working again. Thank you.

**Comment by LordBoos** [comment]
It is possible, that the new version needs all 3 intents. Beta version deffinitely does, because it uses that intent to read message reactions, but I'm not so sure about the regular version, new nextcord finalized the intents object so previous method of requesting the default and adding the two required ones is not possible anymore, now i have to request all instead of default, so that includes Message Content intent, but this intent is then never used in the regular version.

**Comment by LordBoos** [comment]
@Mithrox do you consider this issue resolved? If so, please close this issue. Thank you!

**Comment by Mithrox** [comment]
Hi @LordBoos. Sorry, I did not comment after the last one. It worked when I setup a full new instance of HA, but after I got that working, I could also use the same application on the normal one. So now it's all good, working as a charm :) Thank you so much for the help!
