### ISSUE TITLE
'spotify_artist' always null

### ISSUE THREAD

**Issue by riddlenl** [LordBoos/discord_game#47]
Listening to Spotify doesn't send the Artist to Home Assistant:

listening: Children - Undercatt Remix
listening_url: null
listening_details: null
spotify_artist: null
spotify_title: Children - Undercatt Remix
spotify_album: Children (Undercatt Remix)
spotify_album_cover_url: https://i.scdn.co/image/ab67616d0000b273da1dfc9b715543e53811ac41
spotify_track_id: 539yxbKKHPHrI1vc3BI2Ee
spotify_duration: 0:06:45.071000
spotify_start: 2022-10-02 20:57:26.827000+00:00
spotify_end: 2022-10-02 21:04:11.898000+00:00

I think I see why. In the source code I see "spotify_artists" mixed with "spotify_artist", is that correct?

**Comment by LordBoos** [comment]
Fixed in https://github.com/LordBoos/discord_game/releases/tag/4.2.6
