### ISSUE TITLE
Idea - Use Activities rather than Activity

### ISSUE THREAD

**Issue by C0NTi** [LordBoos/discord_game#5]
In the api you have 

discord_member.activity.name
or 
discord_member.activities

The problem I have with the default behaviour of activity.name is that it shows you the most current activity. So if I fire up a game my and then decide to listen to spotify while in game my activity will display Spotify not the game I'm playing.

![image](https://user-images.githubusercontent.com/29498865/67748515-04a17400-fa23-11e9-9316-5a855d6031c6.png)

I have modified the component to also include the activities feed, as you can see the response is a bit messy, I don't know a thing about python and how to tidy it up, so at the moment Im just using another home assistant sensor..

![image](https://user-images.githubusercontent.com/29498865/67748720-78dc1780-fa23-11e9-9bac-77edc2d6a44e.png)

If this could be incorporated into the component, I could remove all my redundant template sensors, and I could see the true game activity for my friends.

From what I can tell in the responses a game can come in different formats depending on whether its a Discord 'RICH PRESENCE GAME', A discord automatically recognised game or a manually added game.

**Comment by LordBoos** [comment]
Good idea, might as well get some additional information from the discord like song currently listened to etc.

**Comment by LordBoos** [comment]
Implemented in the release 2.0.0: https://github.com/LordBoos/discord_game/releases/tag/2.0.0
