### ISSUE TITLE
Game Values Null

### ISSUE THREAD

**Issue by Bovive** [LordBoos/discord_game#52]
Hello,

I just set this up and it does gather some information, but I am receiving some null values for game details. I have all privileged gateway intents checked. The bot is on the server and in the general channel.

Values that work:
-------------------
game:

Values that are always null:
-------------------
game_state: null
game_details: null
game_image_small: null
game_image_large: null
game_image_small_text: null
game_image_large_text: null
game_image_capsule_231x87: null
game_image_capsule_467x181: null
game_image_capsule_616x353: null
game_image_header: null
game_image_hero_capsule: null
game_image_library_600x900: null
game_image_library_hero: null
game_image_logo: null
game_image_page_bg_raw: null

Any insight as to why this may be would be appreciated. Thank you!

**Comment by LordBoos** [comment]
Hello, some values are null for some games, because they are not available.
Some of the above is however fixed in release 6.0.0
