### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by benji2020** [LordBoos/discord_game#55]
Hi
Great add-on, thanks.
After going round in circles setting it up I noticed a closed ticket saying from now on you set things up via the GUI, but the info here shows a YAML example: info.md

Can't find anything to say you can, but is there a way to manually add a user, or can I only see ones on the server with the bot on it?

Regards
Ben

**Comment by LordBoos** [comment]
Hi, sorry I forget to update the info.md for the new version.
You can only add users that the bot can see on the server, that is Discord limitation.
