### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by UraniumDonut** [LordBoos/discord_game#59]
Pretty much this error message pops up when adding the integration. Worked fine before with the manual yaml integration.

![image](https://github.com/LordBoos/discord_game/assets/75068550/c1aa8f4b-dfbf-449e-930c-1c70da458e87)

**Comment by LordBoos** [comment]
This was reported here https://github.com/LordBoos/discord_game/issues/58 before and solution was to update Home Assistant. Which version of HA are you on right now?

**Comment by UraniumDonut** [comment]
2023.1.7

Looks like that is the reason

**Comment by LordBoos** [comment]
Update HA to latest version or downgrade to Discord Game to 5.0.4 https://github.com/LordBoos/discord_game/releases/tag/5.0.4
