### ISSUE TITLE
Underscores causing issues with discord name detection

### ISSUE THREAD

**Issue by theonetoday** [LordBoos/discord_game#8]
I have multiple people in my configuration.yaml file that are detected just fine. Only one is giving me issues and I believe it is because of the underscores in his name. That's the only thing I can find different from the others. Is there a simple fix to this that I don't know? I'm not a programmer or anything. I tried quotes thinking that may work but no.

Here's the discord name

George_W_#6605

**Comment by xiidoz** [comment]
This should be resolved with #10 .

**Comment by xiidoz** [comment]
Wasn't resolved with #10 , hence #13 .

**Comment by LordBoos** [comment]
Fixed by #13
