### ISSUE TITLE
Photos of discord-users not showing in HA-app

### ISSUE THREAD

**Issue by IQNeoXen** [LordBoos/discord_game#9]
I don't know if this is caused by this integration or by HA itself, so please feel free to close this if you think it's HA's fault ;)

When displaying the discord-user-entities in lovelace, I can see the users profilepictures just fine. When i'm loading the same dashboard in the HA-app, the pictures are gone.

Browser:
![image](https://user-images.githubusercontent.com/20561093/77928179-61da7380-72a8-11ea-93c4-2fab698d91aa.png)

App:
![image](https://user-images.githubusercontent.com/20561093/77928312-8afb0400-72a8-11ea-9544-1834b0435838.png)

**Comment by LordBoos** [comment]
Hi, I've just teste this with multiple accounts and it works fine on my phone. Using official HA app on my Samsung Galaxy Note 8, Android 9.

**Comment by niklaswa** [comment]
That's because Safari and iOS Safari [don't support](https://caniuse.com/#feat=webp) `.webp`.
